name: Pull request

permissions:
  contents: read

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '*.md'
      - 'Proposals/**'

jobs:
  tests:
    name: Test (SwiftPM)
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@main
    with:
      linux_swift_versions: '["nightly-main"]'
      windows_swift_versions: '["nightly-main"]'
      enable_macos_checks: false
      macos_xcode_versions: '["16.3"]'
      macos_versions: '["sequoia"]'
      enable_wasm_sdk_build: true
      wasm_sdk_versions: '["nightly-main"]'
      enable_android_sdk_build: true
      android_sdk_versions: '["nightly-main"]'

  cmake_build:
    name: Build (CMake)
    runs-on: ubuntu-latest
    container: swiftlang/swift:nightly-main-noble
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v1
      - name: Install Dependencies
        shell: bash
        run: apt update && apt install -y cmake ninja-build
      - name: Configure Project
        shell: bash
        run: cmake -G 'Ninja' -B build -S . -DCMAKE_C_COMPILER=clang -DCMAKE_Swift_COMPILER=swiftc -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=YES
      - name: Build Project
        shell: bash
        run: cmake --build build

  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Swift.org"
      license_header_check_enabled: false
      docs_check_enabled: false
      format_check_enabled: false
      unacceptable_language_check_enabled: false
      api_breakage_check_enabled: false
